# Generated by Django 5.1.2 on 2024-10-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tech_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='techs'),
        ),
    ]
